package com.Infinity.MiningDimension.world.feature.thermal;

import com.Infinity.MiningDimension.config.ThermalCommonConfigs;
import com.Infinity.MiningDimension.world.feature.ModPlacedFeatures;
import com.Infinity.MiningDimension.world.feature.ModOrePlacement;
import net.minecraft.core.Holder;
import net.minecraft.data.worldgen.placement.PlacementUtils;
import net.minecraft.world.level.levelgen.VerticalAnchor;
import net.minecraft.world.level.levelgen.placement.HeightRangePlacement;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;

public class ThermalPlacedFeatures {
 public static final Holder<PlacedFeature> THERMAL_APATITE = PlacementUtils.register("imd_thermal_apatite", ThermalConfiguredFeatures.APATITE_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.APATITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_CINNABAR = PlacementUtils.register("imd_thermal_cinnabar", ThermalConfiguredFeatures.CINNABAR_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.CINNABAR_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_NITER = PlacementUtils.register("imd_thermal_niter", ThermalConfiguredFeatures.NITER_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.NITER_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_SULFUR = PlacementUtils.register("imd_thermal_sulfur", ThermalConfiguredFeatures.SULFUR_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.SULFUR_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_TIN = PlacementUtils.register("imd_thermal_tin", ThermalConfiguredFeatures.TIN_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.TIN_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_LEAD = PlacementUtils.register("imd_thermal_lead", ThermalConfiguredFeatures.LEAD_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.LEAD_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_NICKEL = PlacementUtils.register("imd_thermal_nickel", ThermalConfiguredFeatures.NICKEL_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.NICKEL_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_SILVER = PlacementUtils.register("imd_thermal_silver", ThermalConfiguredFeatures.SILVER_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.SILVER_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_RUBY = PlacementUtils.register("imd_thermal_ruby", ThermalConfiguredFeatures.RUBY_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.RUBY_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> THERMAL_SAPPHIRE = PlacementUtils.register("imd_thermal_sapphire", ThermalConfiguredFeatures.SAPPHIRE_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.SAPPHIRE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));

 public static final Holder<PlacedFeature> THERMAL_BITUMINOUS_SAND = PlacementUtils.register("imd_thermal_bituminous_sand", ThermalConfiguredFeatures.BITUMINOUS_SAND_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.BITUMINOUS_SAND_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.sandMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.sandMaxY))));
 public static final Holder<PlacedFeature> THERMAL_BITUMINOUS_RED_SAND = PlacementUtils.register("imd_thermal_bituminous_red_sand", ThermalConfiguredFeatures.BITUMINOUS_RED_SAND_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.BITUMINOUS_RED_SAND_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.redSandMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.redSandMaxY))));
 
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_APATITE = PlacementUtils.register("imd_thermal_deepslate_apatite", ThermalConfiguredFeatures.DEEPSLATE_APATITE_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_APATITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_CINNABAR = PlacementUtils.register("imd_thermal_deepslate_cinnabar", ThermalConfiguredFeatures.DEEPSLATE_CINNABAR_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_CINNABAR_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_NITER = PlacementUtils.register("imd_thermal_deepslate_niter", ThermalConfiguredFeatures.DEEPSLATE_NITER_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_NITER_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_SULFUR = PlacementUtils.register("imd_thermal_deepslate_sulfur", ThermalConfiguredFeatures.DEEPSLATE_SULFUR_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_SULFUR_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_TIN = PlacementUtils.register("imd_thermal_deepslate_tin", ThermalConfiguredFeatures.DEEPSLATE_TIN_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_TIN_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_LEAD = PlacementUtils.register("imd_thermal_deepslate_lead", ThermalConfiguredFeatures.DEEPSLATE_LEAD_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_LEAD_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_NICKEL = PlacementUtils.register("imd_thermal_deepslate_nickel", ThermalConfiguredFeatures.DEEPSLATE_NICKEL_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_NICKEL_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_SILVER = PlacementUtils.register("imd_thermal_deepslate_silver", ThermalConfiguredFeatures.DEEPSLATE_SILVER_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_SILVER_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_RUBY = PlacementUtils.register("imd_thermal_deepslate_ruby", ThermalConfiguredFeatures.DEEPSLATE_RUBY_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_RUBY_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> THERMAL_DEEPSLATE_SAPPHIRE = PlacementUtils.register("imd_thermal_deepslate_sapphire", ThermalConfiguredFeatures.DEEPSLATE_SAPPHIRE_ORE, ModOrePlacement.commonOrePlacement(ThermalCommonConfigs.DEEPSLATE_SAPPHIRE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 
}
