package com.Infinity.Nexus.MiningDimension.world.feature.vaulthunters;

import com.Infinity.Nexus.MiningDimension.config.VaultHunterCommonConfigs;
import com.Infinity.Nexus.MiningDimension.world.feature.ModOrePlacement;
import com.Infinity.Nexus.MiningDimension.world.feature.ModPlacedFeatures;
import net.minecraft.core.Holder;
import net.minecraft.data.worldgen.placement.PlacementUtils;
import net.minecraft.world.level.levelgen.VerticalAnchor;
import net.minecraft.world.level.levelgen.placement.HeightRangePlacement;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;

public class VaultHuntersPlacedFeatures {
 public static final Holder<PlacedFeature> VAUTHUNTERS_ALEXANDRITE = PlacementUtils.register("imd_vaulthunters_alexandrite", VaultHuntersConfiguredFeatures.ALEXANDRITE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.ALEXANDRITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_ASHIUM = PlacementUtils.register("imd_vaulthunters_ashium", VaultHuntersConfiguredFeatures.ASHIUM_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.ASHIUM_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_BENITOITE = PlacementUtils.register("imd_vaulthunters_benitoite", VaultHuntersConfiguredFeatures.BENITOITE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.BENITOITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_BLACK_OPAL = PlacementUtils.register("imd_vaulthunters_black_opal", VaultHuntersConfiguredFeatures.BLACK_OPAL_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.BLACK_OPAL_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_BOMIGNITE = PlacementUtils.register("imd_vaulthunters_bomignite", VaultHuntersConfiguredFeatures.BOMIGNITE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.BOMIGNITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_ECHO = PlacementUtils.register("imd_vaulthunters_echo", VaultHuntersConfiguredFeatures.ECHO_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.ECHO_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_GORGINITE = PlacementUtils.register("imd_vaulthunters_gorginite", VaultHuntersConfiguredFeatures.GORGINITE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.GORGINITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_ISKALLIUM = PlacementUtils.register("imd_vaulthunters_iskallium", VaultHuntersConfiguredFeatures.ISKALLIUM_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.ISKALLIUM_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_LARIMAR = PlacementUtils.register("imd_vaulthunters_larimar", VaultHuntersConfiguredFeatures.LARIMAR_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.LARIMAR_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_PAINITE = PlacementUtils.register("imd_vaulthunters_painite", VaultHuntersConfiguredFeatures.PAINITE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.PAINITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_PETZANITE = PlacementUtils.register("imd_vaulthunters_petzanite", VaultHuntersConfiguredFeatures.PETZANITE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.PETZANITE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_SPARKLETINE = PlacementUtils.register("imd_vaulthunters_sparkletine", VaultHuntersConfiguredFeatures.SPARKLETINE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.SPARKLETINE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_TUBIUM = PlacementUtils.register("imd_vaulthunters_tubium", VaultHuntersConfiguredFeatures.TUBIUM_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.TUBIUM_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_UPALINE = PlacementUtils.register("imd_vaulthunters_upaline", VaultHuntersConfiguredFeatures.UPALINE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.UPALINE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_WUTODIE = PlacementUtils.register("imd_vaulthunters_wutodie", VaultHuntersConfiguredFeatures.WUTODIE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.WUTODIE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_XENIUM = PlacementUtils.register("imd_vaulthunters_xenium", VaultHuntersConfiguredFeatures.XENIUM_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.XENIUM_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> VAUTHUNTERS_VAULT_STONE = PlacementUtils.register("imd_vaulthunters_stone", VaultHuntersConfiguredFeatures.VAULT_STONE_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.VAULT_STONE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));

 public static final Holder<PlacedFeature> VAUTHUNTERS_CHROMATIC_IRON = PlacementUtils.register("imd_vaulthunters_chromatic_iron", VaultHuntersConfiguredFeatures.CHROMATIC_IRON_ORE, ModOrePlacement.commonOrePlacement(VaultHunterCommonConfigs.CHROMATIC_IRON_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));

}