package com.Infinity.MiningDimension.world.feature.minecraft;

import com.Infinity.MiningDimension.config.MinecraftCommonConfigs;
import com.Infinity.MiningDimension.world.feature.ModOrePlacement;
import com.Infinity.MiningDimension.world.feature.ModPlacedFeatures;
import net.minecraft.core.Holder;
import net.minecraft.data.worldgen.placement.PlacementUtils;
import net.minecraft.world.level.levelgen.VerticalAnchor;
import net.minecraft.world.level.levelgen.placement.HeightRangePlacement;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;

public class MinecraftPlacedFeatures {
 public static final Holder<PlacedFeature> MINECRAFT_COAL = PlacementUtils.register("imd_coal", MinecraftConfiguredFeatures.COAL_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.COAL_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_COPPER = PlacementUtils.register("imd_copper", MinecraftConfiguredFeatures.COPPER_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.COPPER_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_IRON = PlacementUtils.register("imd_iron", MinecraftConfiguredFeatures.IRON_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.IRON_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_GOLD = PlacementUtils.register("imd_gold", MinecraftConfiguredFeatures.GOLD_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.GOLD_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_LAPIS = PlacementUtils.register("imd_lapis", MinecraftConfiguredFeatures.LAPIS_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.LAPIS_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_REDSTONE = PlacementUtils.register("imd_redstone", MinecraftConfiguredFeatures.REDSTONE_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.REDSTONE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DIAMOND = PlacementUtils.register("imd_diamond", MinecraftConfiguredFeatures.DIAMOND_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DIAMOND_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_EMERALD = PlacementUtils.register("imd_emerald", MinecraftConfiguredFeatures.EMERALD_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.EMERALD_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.stoneMaxY))));

 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_COAL = PlacementUtils.register("imd_deepslate_coal", MinecraftConfiguredFeatures.DEEPSLATE_COAL_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_COAL_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_COPPER = PlacementUtils.register("imd_deepslate_copper", MinecraftConfiguredFeatures.DEEPSLATE_COPPER_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_COPPER_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_IRON = PlacementUtils.register("imd_deepslate_iron", MinecraftConfiguredFeatures.DEEPSLATE_IRON_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_IRON_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_GOLD = PlacementUtils.register("imd_deepslate_gold", MinecraftConfiguredFeatures.DEEPSLATE_GOLD_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_GOLD_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_LAPIS = PlacementUtils.register("imd_deepslate_lapis", MinecraftConfiguredFeatures.DEEPSLATE_LAPIS_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_LAPIS_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_REDSTONE = PlacementUtils.register("imd_deepslate_redstone", MinecraftConfiguredFeatures.DEEPSLATE_REDSTONE_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_REDSTONE_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_DIAMOND = PlacementUtils.register("imd_deepslate_diamond", MinecraftConfiguredFeatures.DEEPSLATE_DIAMOND_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_DIAMOND_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_DEEPSLATE_EMERALD = PlacementUtils.register("imd_deepslate_emerald", MinecraftConfiguredFeatures.DEEPSLATE_EMERALD_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.DEEPSLATE_EMERALD_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.deepslateMaxY))));

 public static final Holder<PlacedFeature> MINECRAFT_NETHER_GOLD = PlacementUtils.register("imd_nether_gold", MinecraftConfiguredFeatures.NETHER_GOLD_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.NETHER_GOLD_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(-ModPlacedFeatures.netherrackMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.netherrackMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_NETHER_QUARTZ = PlacementUtils.register("imd_nether_quartz", MinecraftConfiguredFeatures.NETHER_QUARTZ_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.NETHER_QUARTZ_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(-ModPlacedFeatures.netherrackMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.netherrackMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_NETHER_DEBRIS = PlacementUtils.register("imd_nether_debris", MinecraftConfiguredFeatures.NETHER_DEBRIS_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.NETHER_DEBRIS_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(-ModPlacedFeatures.netherrackMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.netherrackMaxY))));
 public static final Holder<PlacedFeature> MINECRAFT_NETHER_SOULSAND = PlacementUtils.register("imd_nether_soulsand", MinecraftConfiguredFeatures.NETHER_SOULSAND_ORE, ModOrePlacement.commonOrePlacement(MinecraftCommonConfigs.NETHER_SOULSAND_VEINS.get(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(-ModPlacedFeatures.netherrackMinY), VerticalAnchor.aboveBottom(ModPlacedFeatures.netherrackMaxY))));
}
